services:
  - type: web
    name: doctor-app
    env: php
    branch: main
    buildCommand: "composer install" # Optional, if using Composer
    startCommand: "php -S 0.0.0.0:10000" # Command to run the PHP app
    envVars:
      - key: PORT
        value: "10000"
